#WHYOHWHY

    (.venv) PS D:\git\diablo4\test_tox> python .\src\a.py
    Hello World
    (.venv) PS D:\git\diablo4\test_tox> tox
    py312: commands[0]> pytest
    ======================================================================================================================================= test session starts ========================================================================================================================================
    platform win32 -- Python 3.12.0b4, pytest-7.4.0, pluggy-1.2.0
    cachedir: .tox\py312\.pytest_cache
    rootdir: D:\git\diablo4\test_tox
    collected 0 items / 1 error
    
    ============================================================================================================================================== ERRORS ==============================================================================================================================================
    _________________________________________________________________________________________________________________________________ ERROR collecting tests/test_a.py _________________________________________________________________________________________________________________________________
    ImportError while importing test module 'D:\git\diablo4\test_tox\tests\test_a.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    C:\Users\rotte\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90: in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    tests\test_a.py:1: in <module>
        from src.a import A
    src\a.py:1: in <module>
        from b import B
    E   ModuleNotFoundError: No module named 'b'
    ===================================================================================================================================== short test summary info ======================================================================================================================================
    ERROR tests/test_a.py
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ========================================================================================================================================= 1 error in 0.06s =========================================================================================================================================
    py312: exit 2 (0.28 seconds) D:\git\diablo4\test_tox> pytest pid=30840
      py312: FAIL code 2 (0.31=setup[0.03]+cmd[0.28] seconds)
      evaluation failed :( (0.41 seconds)